const CUSTOMER_MANAGEMENT_SAGA_ACTION_TYPE = {
  FETCH_CUSTOMERS_SAGA: "FETCH_CUSTOMERS_SAGA",
  FETCH_CUSTOMERS_SUCCESS_SAGA: "FETCH_CUSTOMERS_SUCCESS_SAGA",
  FETCH_CUSTOMERS_FAIL_SAGA: "FETCH_CUSTOMERS_FAIL_SAGA",
};

export default CUSTOMER_MANAGEMENT_SAGA_ACTION_TYPE;
