const CUSTOMER_MANAGEMENT_ACTION_TYPE = {
  FETCH_CUSTOMERS: "FETCH_CUSTOMERS",
  FETCH_CUSTOMERS_SUCCESS: "FETCH_CUSTOMERS_SUCCESS",
  FETCH_CUSTOMERS_FAIL: "FETCH_CUSTOMERS_FAIL",
};

export default CUSTOMER_MANAGEMENT_ACTION_TYPE;
